// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo5DcGq2EHwN0XN7l32Mj5ltXGq0HYRrY',
    appId: '1:515530161188:web:909c45a64e928723586cb1',
    messagingSenderId: '515530161188',
    projectId: 'cool-beanbag-355116',
    authDomain: 'cool-beanbag-355116.firebaseapp.com',
    storageBucket: 'cool-beanbag-355116.appspot.com',
    measurementId: 'G-DBG4CSJZ0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaOabatY2bheZOiD8YnI_D8loaDOF6WqM',
    appId: '1:515530161188:android:b2eab7f36d46ae03586cb1',
    messagingSenderId: '515530161188',
    projectId: 'cool-beanbag-355116',
    storageBucket: 'cool-beanbag-355116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6i2BCZjYxKNYaB7lM-6G4bgjn2IAElGA',
    appId: '1:515530161188:ios:77048f79240d7c52586cb1',
    messagingSenderId: '515530161188',
    projectId: 'cool-beanbag-355116',
    storageBucket: 'cool-beanbag-355116.appspot.com',
    iosClientId: '515530161188-6em8bou6f47mqqlukre85q7vmet5lkbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduapge2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6i2BCZjYxKNYaB7lM-6G4bgjn2IAElGA',
    appId: '1:515530161188:ios:77048f79240d7c52586cb1',
    messagingSenderId: '515530161188',
    projectId: 'cool-beanbag-355116',
    storageBucket: 'cool-beanbag-355116.appspot.com',
    iosClientId: '515530161188-6em8bou6f47mqqlukre85q7vmet5lkbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduapge2',
  );
}
