name: build-preview-android
run-name: Building a preview version apk file
permissions:
  contents: write
  packages: write
  deployments: write
  issues: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
on:
  push:
    branches-ignore:
      - build-prerelease
      - build-release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.12'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:' # optional, change this to force refresh cache
        architecture: x64
    - name: Create the Keystore
      env:
        KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
      run: |
        # import keystore from secrets
        echo $KEYSTORE_B64 | base64 -d > $RUNNER_TEMP/keystore.jks
    - name: Create key.properties
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASS }}
        KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASS }}
      run: |
        echo -e "storePassword=$KEYSTORE_PASSWORD\nkeyPassword=$KEY_PASSWORD\nkeyAlias=$KEY_ALIAS\nstoreFile=$RUNNER_TEMP/keystore.jks" > android/key.properties
    - uses: paulhatch/semantic-version@v5.0.2
      with:
        # The prefix to use to identify tags
        tag_prefix: "v"
        # A string which, if present in a git commit, indicates that a change represents a
        # major (breaking) change, supports regular expressions wrapped with '/'
        major_pattern: "(MAJOR)"
        # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
        major_regexp_flags: ""
        # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
        minor_pattern: "(MINOR)"
        # A string which indicates the flags used by the `minor_pattern` regular expression. Supported flags: idgs
        minor_regexp_flags: ""
        # A string to determine the format of the version output
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - run: flutter pub get
    - run: flutter analyze .
    - run: flutter gen-l10n
    - run: flutter build apk --build-name ${{ steps.semvers.outputs.patch }} --dart-define=BVS="Preview ${{ steps.semvers.outputs.patch }} GitHub"
    - run: cp "build/app/outputs/apk/release/app-release.apk" "EduPage2-${{ steps.semvers.outputs.v_patch }}.apk"
#    - uses: "marvinpinto/action-automatic-releases@latest"
#      with:
#        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        automatic_release_tag: "${{ steps.semvers.outputs.v_patch }}"
#        prerelease: false
#        title: "EduPage2 Beta ${{ steps.semvers.outputs.v_patch }}"
#        files: |
#          EduPage2-${{ steps.semvers.outputs.v_patch }}.apk
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: "EduPage2-${{ steps.semvers.outputs.v_patch }}.apk"
