name: build-prerelease-android
run-name: Building a prerelease version apk file
permissions:
  contents: write
  packages: write
  deployments: write
  issues: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:' # optional, change this to force refresh cache
        architecture: x64
    - name: Create the Keystore
      env:
        KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
      run: |
        # import keystore from secrets
        echo $KEYSTORE_B64 | base64 -d > $RUNNER_TEMP/keystore.jks
    - name: Create key.properties
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASS }}
        KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASS }}
      run: |
        echo -e "storePassword=$KEYSTORE_PASSWORD\nkeyPassword=$KEY_PASSWORD\nkeyAlias=$KEY_ALIAS\nstoreFile=$RUNNER_TEMP/keystore.jks" > android/key.properties
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - run: flutter pub get
    - run: flutter analyze .
    - run: flutter gen-l10n
    - run: flutter test --coverage --dart-define=USERNAME=${{ secrets.USERNAME }} --dart-define=PASSWORD=${{ secrets.PASSWORD }}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
