name: test-coverage
run-name: Test the project coverage and upload to codecov
permissions:
  contents: write
  packages: write
  deployments: write
  issues: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:" # optional, change this to force refresh cache
          architecture: x64
      - run: flutter pub get
      - run: dart pub global activate full_coverage
      - run: flutter analyze .
      - run: flutter gen-l10n
      - run: dart pub global run full_coverage
      - run: flutter test --coverage
      - name: Rename coverage file
        run: mv coverage/lcov.info coverage/test-lcov.info # Rename the coverage file to avoid overwriting it
      #      - name: run integration tests
      #        uses: reactivecircus/android-emulator-runner@v2
      #        with:
      #          api-level: 31
      #          arch: x86_64
      #          profile: pixel_6_pro
      #          avd-name: Pixel_6_Pro_API_31
      #          force-avd-creation: false
      #          ram-size: 4096M
      #          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #          disable-animations: true
      #          script: flutter test integration_test/app_test.dart --coverage --dart-define=USERNAME=${{ secrets.USERNAME }} --dart-define=PASSWORD=${{ secrets.PASSWORD }} --dart-define=NAME="${{ secrets.NAME }}"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/lcov.info,./coverage/test-lcov.info
